apiVersion: v1
kind: Service
metadata: 
  name: cluster-ip-service
  labels:
    app: myservice
spec:
  type: clusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp
    type: front-end
